# Source code for http://www.elfische.ru website.
# Released under the MIT license (http://opensource.org/licenses/MIT).

application: elfische-new
version: 5-1-15
runtime: python27
api_version: 1
threadsafe: true


builtins:
- remote_api: on
- deferred: on

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest

inbound_services:
- warmup
- channel_presence

skip_files:
- ^local_settings.py
- ^(.*/)?.*\.py[co]

handlers:
- url: /static/fonts
  static_dir: static/fonts
- url: /.*
  script: main.app
